version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - |
        case "$CODEBUILD_WEBHOOK_HEAD_REF" in
          refs/heads/*) export VERSIONING_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/} ;;
          refs/tags/*) export VERSIONING_GIT_TAG=${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/} ;;
        esac
      - echo $VERSIONING_GIT_BRANCH
      - echo $VERSIONING_GIT_TAG
      - mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q

cache:
  paths:
    - '/root/.m2/**/*'