version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - |
        if [[ "$CODEBUILD_WEBHOOK_HEAD_REF" = refs/heads/feature/* ]]; then
            export VERSIONING_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/feature/};
        fi
      - echo $VERSIONING_GIT_BRANCH
      - mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q

cache:
  paths:
    - '/root/.m2/**/*'